apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-popp
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://medlemskap-popp.intern.nav.no
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: omsorgsopptjening-bestem-pensjonsopptjening
          namespace: pensjonopptjening
          cluster: prod-gcp
    outbound:
      rules:
      external:
        - host: login.microsoftonline.com
  env:
    - name: MEDL_OPPSLAG_BASE_URL
      value: http://medlemskap-oppslag.medlemskap.svc.cluster.local
    - name: MEDL_OPPSLAG_CLIENT_ID
      value: 23600ac9-019c-445d-87a4-2df4996e6f63
